INSERT INTO FARMERS VALUES ("jsmith", "James", "Smith", "010-1234-1234", "jsmith@gmail.com", 1, "22 Bamgogae-ro 1-gil Gangnam-gu", "Seoul Special Metropolitan City" );
INSERT INTO FARMERS VALUES ("pstewart", "Peter", "Stewart", "010-2345-2345", "pstewart@gmail.com", 2,"14 Teheran-ro 82-gil Gangnam-gu", "Seoul Special Metropolitan City" );
INSERT INTO FARMERS VALUES ("jhall", "John", "Hall", "010-3456-3456", "jhall@gmail.com", 3, "53 Gyeongdongsijang-ro 2-gil Dongdaemun-gu", "Seoul Special Metropolitan City" );
INSERT INTO FARMERS VALUES ("cmorris", "Cathy", "Morris", "010-4567-4567", "cmorris@gmail.com", 4, "25 Dogok-ro 64-gil Songpa-gu", "Seoul Special Metropolitan City" );
INSERT INTO FARMERS VALUES ("kbell", "Katherine", "Bell", "010-5678-5678", "kbell@gmail.com", 2, "35 Ganchon-ro 27beon-gil Seo-gu", "Incheon Metropolitan City" );
INSERT INTO FARMERS VALUES ("ahyes", "Abigail", "Hayes", "010-4321-4321", "ahyes@gmail.com", 5, "578 Maesohol-ro Nam-gu", "Incheon Metropolitan City" );
INSERT INTO FARMERS VALUES ("asanders", "Addison", "Sanders", "010-5432-5432", "asanders@gmail.com", 3,"7 Hogupo-ro 889beon-gil Namdong-gu", "Incheon Metropolitan City");
INSERT INTO FARMERS VALUES ("bcollins", "Benjamin", "Collins", "010-6543-6543", "bcollins@gmail.com", 2, "20 Pyeongnae-ro 29beonan-gil", "Namyangju" );
INSERT INTO FARMERS VALUES ("cgriffin", "Christopher", "Griffin","010-7654-7654","cgriffin@gmail.com", 1, "31 Haenggung-ro 62beon-gil Paldal-gu", "Suwon");
INSERT INTO FARMERS VALUES ("dcampbell", "David", "Campbell", "010-8765-8765", "dcampbell@gmail.com", 4, "22 Chanumul 2-gil", "Siheung" );
