INSERT INTO BUYERS VALUES ("kross", "Kelly", "Ross", "010-6789-6789", "kross@gmail.com", "21 Seolleung-ro 8-gil", "Seoul Special Metropolitan City" );
INSERT INTO BUYERS VALUES ("swood", "Scott", "Wood", "010-7890-7890", "swood@gmail.com", "42 Gangdongchogyo-gil", "Gangneung" );
INSERT INTO BUYERS VALUES ("bcooper", "Bob", "Cooper", "010-8901-8901", "bcooper@gmail.com", "34 Gyeongancheon-ro 258beon-gil Cheoin-gu", "Yongin" );
INSERT INTO BUYERS VALUES ("kmorgan", "Kate", "Morgan", "010-9012-9012", "kmorgan@gmail.com", "39 Gambuk-ro", "Hanam" );
INSERT INTO BUYERS VALUES ("bperry", "Brian", "Perry", "010-0123-0123", "bperry@gmail.com", "70 Jangan-gil", "Pyeongtaek" );
INSERT INTO BUYERS VALUES ("dparker", "Daniel", "Parker", "010-1324-1324", "dparker@gmail.com", "31 Seokdae-ro Haeundae-gu", "Busan Metropolitan City" );
INSERT INTO BUYERS VALUES ("eevans", "Elizabeth", "Evans", "010-2435-2435", "eevans@gmail.com", "119 Songdomunhwa-ro Yeonsu-gu", "Incheon Metropolitan City" );
INSERT INTO BUYERS VALUES ("erussell", "Emily", "Russell", "010-3546-3546", "erussell@gmail.com", "69 Namsan-ro", "Jecheon" );
INSERT INTO BUYERS VALUES ("gbryant", "Grace", "Bryant", "010-4657-4657", "gbryant@gmail.com", "683 Donghaean-ro Dong-gu", "Ulsan Metropolitan City" );
INSERT INTO BUYERS VALUES ("lgray", "Lily", "Gray", "010-5768-5768", "lgray@gmail.com", "1 Hureung-gil Dong-gu", "Ulsan Metropolitan City" );