<<<<<<< HEAD
INSERT INTO CROPS VALUES ("Pecan",     "nuts",     "category", "kg");
INSERT INTO CROPS VALUES ("Watermelon","fruit",    "category", "for each");
INSERT INTO CROPS VALUES ("Pumpkin",   "fruit",    "category", "kg");
INSERT INTO CROPS VALUES ("Rice",      "grain",    "close growing", "kg");
INSERT INTO CROPS VALUES ("Strawberry","fruit",    "category", "kg");
INSERT INTO CROPS VALUES ("Tomato",    "vegetable","category", "kg");
INSERT INTO CROPS VALUES ("Mango",     "fruit",    "category", "kg");
INSERT INTO CROPS VALUES ("Lemon",     "fruit ",   "category", "kg");
INSERT INTO CROPS VALUES ("Potato",    "vegetable","row crop", "kg");
INSERT INTO CROPS VALUES ("Dill",      "herb",     "category", "kg");
INSERT INTO CROPS VALUES ("Eggplant",  "fruit",    "category", "kg");
INSERT INTO CROPS VALUES ("Grapefruit","fruit",    "category", "for each");
INSERT INTO CROPS VALUES ("Kiwi",      "fruit",    "category", "for each");
INSERT INTO CROPS VALUES ("Kale",      "vegetable","category", "kg");
INSERT INTO CROPS VALUES ("Apple",     "fruit",    "category", "kg");
INSERT INTO CROPS VALUES ("Apricot",   "fruit",    "category", "kg");
INSERT INTO CROPS VALUES ("Avocado",   "fruit",    "category", "for each");
INSERT INTO CROPS VALUES ("Cabbage",   "vegetable","category", "for each");
INSERT INTO CROPS VALUES ("Carrot",    "vegetable","category", "kg");
=======
INSERT INTO CROPS VALUES ("Pecan",     "nuts",     "category", "kg");
INSERT INTO CROPS VALUES ("Watermelon","fruit",    "category", "for each");
INSERT INTO CROPS VALUES ("Pumpkin",   "fruit",    "category", "kg");
INSERT INTO CROPS VALUES ("Rice",      "grain",    "close growing", "kg");
INSERT INTO CROPS VALUES ("Strawberry","fruit",    "category", "kg");
INSERT INTO CROPS VALUES ("Tomato",    "vegetable","category", "kg");
INSERT INTO CROPS VALUES ("Mango",     "fruit",    "category", "kg");
INSERT INTO CROPS VALUES ("Lemon",     "fruit ",   "category", "kg");
INSERT INTO CROPS VALUES ("Potato",    "vegetable","row crop", "kg");
INSERT INTO CROPS VALUES ("Dill",      "herb",     "category", "kg");
INSERT INTO CROPS VALUES ("Eggplant",  "fruit",    "category", "kg");
INSERT INTO CROPS VALUES ("Grapefruit","fruit",    "category", "for each");
INSERT INTO CROPS VALUES ("Kiwi",      "fruit",    "category", "for each");
INSERT INTO CROPS VALUES ("Kale",      "vegetable","category", "kg");
INSERT INTO CROPS VALUES ("Apple",     "fruit",    "category", "kg");
INSERT INTO CROPS VALUES ("Apricot",   "fruit",    "category", "kg");
INSERT INTO CROPS VALUES ("Avocado",   "fruit",    "category", "for each");
INSERT INTO CROPS VALUES ("Cabbage",   "vegetable","category", "for each");
INSERT INTO CROPS VALUES ("Carrot",    "vegetable","category", "kg");
>>>>>>> db76220d8470c7078290389a5aee6987fa93da45
INSERT INTO CROPS VALUES ("Celery",    "vegetable","category", "kg");