<<<<<<< HEAD
INSERT INTO FARMER_REPUTATIONS VALUES (1, "not recommended");
INSERT INTO FARMER_REPUTATIONS VALUES (2, "less than neutral");
INSERT INTO FARMER_REPUTATIONS VALUES (3, "neutral");
INSERT INTO FARMER_REPUTATIONS VALUES (4, "trust-worthy");
=======
INSERT INTO FARMER_REPUTATIONS VALUES (1, "not recommended");
INSERT INTO FARMER_REPUTATIONS VALUES (2, "less than neutral");
INSERT INTO FARMER_REPUTATIONS VALUES (3, "neutral");
INSERT INTO FARMER_REPUTATIONS VALUES (4, "trust-worthy");
>>>>>>> db76220d8470c7078290389a5aee6987fa93da45
INSERT INTO FARMER_REPUTATIONS VALUES (5, "super farmer");